# Generated by Django 4.0 on 2021-12-31 14:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phoneNumber',
            field=models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(regex='(^\\+98|0098|98|0)?9\\d{9}$')]),
        ),
    ]
