# Generated by Django 4.0 on 2021-12-31 14:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='LifeInsurnaceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(regex='(^\\+98|0098|98|0)?9\\d{9}$')])),
                ('age', models.PositiveSmallIntegerField()),
                ('BMI', models.PositiveSmallIntegerField()),
                ('smoker', models.BooleanField(default=False)),
                ('cigarette_count', models.PositiveIntegerField(default=0)),
                ('hookah_count', models.PositiveIntegerField(default=0)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LifeInsurance.branch')),
            ],
        ),
    ]
